Mox.defmock(MockReader, for: Pipeline.Reader)
Mox.defmock(MockTopic, for: Pipeline.Writer)
Mox.defmock(MockTable, for: Pipeline.Writer)
Mox.defmock(MockBuffer, for: Pipeline.Writer)
Mox.defmock(MockMetricCollector, for: StreamingMetrics.MetricCollector)
