name: Commenter
on: [pull_request]

jobs:
  check-mix-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Elixir
        uses: actions/setup-elixir@v1.2.0
        with:
          # Version range or exact version of Elixir to use
          elixir-version: 1.9
          otp-version: 22.2
          runs-on: ubuntu-latest
      - name: Check App versions
        run: echo "::set-output name=pr_message::$(elixir -r differ.exs -e 'Differ.cli')"
        id: differ
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ${{ steps.differ.outputs.message }}
      - name: Comment PR (Static)
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Hello there!
